require 'pry'
require 'nokogiri'
require 'open-uri'
require_relative '../lib/maximumfun/CLI'
require_relative '../lib/maximumfun/scraper'
require_relative '../lib/maximumfun/podcast'
require_relative '../lib/maximumfun/version'
require_relative '../lib/maximumfun/episode'